// Maps E.164 calling code prefixes to a representative IANA timezone.
// Used to display the contact's local time alongside the user's local time.
// Not exhaustive, but covers most common WhatsApp markets we see.

const PREFIX_TO_TZ: Array<[string, string]> = [
  // longer prefixes first
  ["1242", "America/Nassau"],
  ["1246", "America/Barbados"],
  ["1264", "America/Anguilla"],
  ["1268", "America/Antigua"],
  ["1284", "America/Tortola"],
  ["1340", "America/St_Thomas"],
  ["1345", "America/Cayman"],
  ["1441", "Atlantic/Bermuda"],
  ["1473", "America/Grenada"],
  ["1649", "America/Grand_Turk"],
  ["1664", "America/Montserrat"],
  ["1670", "Pacific/Saipan"],
  ["1671", "Pacific/Guam"],
  ["1684", "Pacific/Pago_Pago"],
  ["1721", "America/Lower_Princes"],
  ["1758", "America/St_Lucia"],
  ["1767", "America/Dominica"],
  ["1784", "America/St_Vincent"],
  ["1809", "America/Santo_Domingo"],
  ["1829", "America/Santo_Domingo"],
  ["1849", "America/Santo_Domingo"],
  ["1868", "America/Port_of_Spain"],
  ["1869", "America/St_Kitts"],
  ["1876", "America/Jamaica"],
  ["1939", "America/Puerto_Rico"],
  ["7", "Europe/Moscow"], // RU/KZ - simplified
  ["20", "Africa/Cairo"],
  ["27", "Africa/Johannesburg"],
  ["30", "Europe/Athens"],
  ["31", "Europe/Amsterdam"],
  ["32", "Europe/Brussels"],
  ["33", "Europe/Paris"],
  ["34", "Europe/Madrid"],
  ["36", "Europe/Budapest"],
  ["39", "Europe/Rome"],
  ["40", "Europe/Bucharest"],
  ["41", "Europe/Zurich"],
  ["43", "Europe/Vienna"],
  ["44", "Europe/London"],
  ["45", "Europe/Copenhagen"],
  ["46", "Europe/Stockholm"],
  ["47", "Europe/Oslo"],
  ["48", "Europe/Warsaw"],
  ["49", "Europe/Berlin"],
  ["51", "America/Lima"],
  ["52", "America/Mexico_City"],
  ["53", "America/Havana"],
  ["54", "America/Argentina/Buenos_Aires"],
  ["55", "America/Sao_Paulo"],
  ["56", "America/Santiago"],
  ["57", "America/Bogota"],
  ["58", "America/Caracas"],
  ["60", "Asia/Kuala_Lumpur"],
  ["61", "Australia/Sydney"],
  ["62", "Asia/Jakarta"],
  ["63", "Asia/Manila"],
  ["64", "Pacific/Auckland"],
  ["65", "Asia/Singapore"],
  ["66", "Asia/Bangkok"],
  ["81", "Asia/Tokyo"],
  ["82", "Asia/Seoul"],
  ["84", "Asia/Ho_Chi_Minh"],
  ["86", "Asia/Shanghai"],
  ["90", "Europe/Istanbul"],
  ["91", "Asia/Kolkata"],
  ["92", "Asia/Karachi"],
  ["93", "Asia/Kabul"],
  ["94", "Asia/Colombo"],
  ["95", "Asia/Yangon"],
  ["98", "Asia/Tehran"],
  ["211", "Africa/Juba"],
  ["212", "Africa/Casablanca"],
  ["213", "Africa/Algiers"],
  ["216", "Africa/Tunis"],
  ["218", "Africa/Tripoli"],
  ["220", "Africa/Banjul"],
  ["221", "Africa/Dakar"],
  ["222", "Africa/Nouakchott"],
  ["223", "Africa/Bamako"],
  ["224", "Africa/Conakry"],
  ["225", "Africa/Abidjan"],
  ["226", "Africa/Ouagadougou"],
  ["227", "Africa/Niamey"],
  ["228", "Africa/Lome"],
  ["229", "Africa/Porto-Novo"],
  ["230", "Indian/Mauritius"],
  ["231", "Africa/Monrovia"],
  ["232", "Africa/Freetown"],
  ["233", "Africa/Accra"],
  ["234", "Africa/Lagos"],
  ["235", "Africa/Ndjamena"],
  ["236", "Africa/Bangui"],
  ["237", "Africa/Douala"],
  ["238", "Atlantic/Cape_Verde"],
  ["239", "Africa/Sao_Tome"],
  ["240", "Africa/Malabo"],
  ["241", "Africa/Libreville"],
  ["242", "Africa/Brazzaville"],
  ["243", "Africa/Kinshasa"],
  ["244", "Africa/Luanda"],
  ["245", "Africa/Bissau"],
  ["248", "Indian/Mahe"],
  ["249", "Africa/Khartoum"],
  ["250", "Africa/Kigali"],
  ["251", "Africa/Addis_Ababa"],
  ["252", "Africa/Mogadishu"],
  ["253", "Africa/Djibouti"],
  ["254", "Africa/Nairobi"],
  ["255", "Africa/Dar_es_Salaam"],
  ["256", "Africa/Kampala"],
  ["257", "Africa/Bujumbura"],
  ["258", "Africa/Maputo"],
  ["260", "Africa/Lusaka"],
  ["261", "Indian/Antananarivo"],
  ["263", "Africa/Harare"],
  ["264", "Africa/Windhoek"],
  ["265", "Africa/Blantyre"],
  ["266", "Africa/Maseru"],
  ["267", "Africa/Gaborone"],
  ["268", "Africa/Mbabane"],
  ["269", "Indian/Comoro"],
  ["297", "America/Aruba"],
  ["298", "Atlantic/Faroe"],
  ["299", "America/Godthab"],
  ["350", "Europe/Gibraltar"],
  ["351", "Europe/Lisbon"],
  ["352", "Europe/Luxembourg"],
  ["353", "Europe/Dublin"],
  ["354", "Atlantic/Reykjavik"],
  ["355", "Europe/Tirane"],
  ["356", "Europe/Malta"],
  ["357", "Asia/Nicosia"],
  ["358", "Europe/Helsinki"],
  ["359", "Europe/Sofia"],
  ["370", "Europe/Vilnius"],
  ["371", "Europe/Riga"],
  ["372", "Europe/Tallinn"],
  ["373", "Europe/Chisinau"],
  ["374", "Asia/Yerevan"],
  ["375", "Europe/Minsk"],
  ["376", "Europe/Andorra"],
  ["377", "Europe/Monaco"],
  ["378", "Europe/San_Marino"],
  ["380", "Europe/Kyiv"],
  ["381", "Europe/Belgrade"],
  ["382", "Europe/Podgorica"],
  ["383", "Europe/Belgrade"],
  ["385", "Europe/Zagreb"],
  ["386", "Europe/Ljubljana"],
  ["387", "Europe/Sarajevo"],
  ["389", "Europe/Skopje"],
  ["420", "Europe/Prague"],
  ["421", "Europe/Bratislava"],
  ["423", "Europe/Vaduz"],
  ["500", "Atlantic/Stanley"],
  ["501", "America/Belize"],
  ["502", "America/Guatemala"],
  ["503", "America/El_Salvador"],
  ["504", "America/Tegucigalpa"],
  ["505", "America/Managua"],
  ["506", "America/Costa_Rica"],
  ["507", "America/Panama"],
  ["509", "America/Port-au-Prince"],
  ["591", "America/La_Paz"],
  ["592", "America/Guyana"],
  ["593", "America/Guayaquil"],
  ["595", "America/Asuncion"],
  ["598", "America/Montevideo"],
  ["673", "Asia/Brunei"],
  ["852", "Asia/Hong_Kong"],
  ["853", "Asia/Macau"],
  ["855", "Asia/Phnom_Penh"],
  ["856", "Asia/Vientiane"],
  ["880", "Asia/Dhaka"],
  ["886", "Asia/Taipei"],
  ["960", "Indian/Maldives"],
  ["961", "Asia/Beirut"],
  ["962", "Asia/Amman"],
  ["963", "Asia/Damascus"],
  ["964", "Asia/Baghdad"],
  ["965", "Asia/Kuwait"],
  ["966", "Asia/Riyadh"],
  ["967", "Asia/Aden"],
  ["968", "Asia/Muscat"],
  ["970", "Asia/Hebron"],
  ["971", "Asia/Dubai"],
  ["972", "Asia/Jerusalem"],
  ["973", "Asia/Bahrain"],
  ["974", "Asia/Qatar"],
  ["975", "Asia/Thimphu"],
  ["976", "Asia/Ulaanbaatar"],
  ["977", "Asia/Kathmandu"],
  ["992", "Asia/Dushanbe"],
  ["993", "Asia/Ashgabat"],
  ["994", "Asia/Baku"],
  ["995", "Asia/Tbilisi"],
  ["996", "Asia/Bishkek"],
  ["998", "Asia/Tashkent"],
  // single-digit fallbacks last
  ["1", "America/New_York"],
];

export function timezoneForPhone(phone?: string | null): string | null {
  if (!phone) return null;
  const digits = phone.replace(/\D/g, "");
  if (!digits) return null;
  for (const [prefix, tz] of PREFIX_TO_TZ) {
    if (digits.startsWith(prefix)) return tz;
  }
  return null;
}

export function formatLocalTimeForPhone(
  phone?: string | null,
  date: Date = new Date(),
): { time: string; tz: string; offset: string } | null {
  const tz = timezoneForPhone(phone);
  if (!tz) return null;
  try {
    const time = new Intl.DateTimeFormat([], {
      hour: "2-digit",
      minute: "2-digit",
      timeZone: tz,
      hour12: false,
    }).format(date);
    // Compute offset string like "+05:30"
    const dtf = new Intl.DateTimeFormat("en-US", {
      timeZone: tz,
      timeZoneName: "shortOffset",
    });
    const parts = dtf.formatToParts(date);
    const off = parts.find((p) => p.type === "timeZoneName")?.value ?? "";
    const offset = off.replace("GMT", "UTC");
    return { time, tz, offset };
  } catch {
    return null;
  }
}
