project_id = "xglfamaaotmwulglwcui"

[functions.google-sheets]
verify_jwt = false

[functions.admin-clients]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.generate-ai-seo-report]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.calendly-webhook]
verify_jwt = false

[functions.register-calendly-webhook]
verify_jwt = false
